### ISSUE TITLE
Misleading README Prerequisites

### ISSUE THREAD

**Issue by VetleViking** [kaskil12/TerminalStudio#5]
All of the prerequisites listed are not strictly needed, they should be just recommended

- Windows is not required, you can compile and run c++ on any other OS
- Visual Studio and Visual Studio Code are just text editors, and are just prefrences, not something you need
- Any c++ compilers would work, not just g++

**Comment by VetleViking** [comment]
but ok, ill fix it :)

**Comment by VetleViking** [comment]
[](https://github.com/kaskil12/TerminalStudio/pull/8)
fixed here.

**Comment by kaskil12** [comment]
merged
